environment:
  PYTHON_HOME: "C:\\Python37"

  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      ARCH_BUILD: x86_64
      ARCH: x86
      CONAN_MAKE_PROGRAM: C:\\tools\\mingw64\\binmingw32-make.exe
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      ARCH_BUILD: x86_64
      ARCH: x86_64
      CONAN_MAKE_PROGRAM: C:\\tools\\mingw64\\binmingw32-make.exe
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      ARCH_BUILD: x86_64
      ARCH: armv7
      CONAN_MAKE_PROGRAM: C:\\tools\\mingw64\\binmingw32-make.exe
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      ARCH_BUILD: x86_64
      ARCH: armv8
      CONAN_MAKE_PROGRAM: C:\\tools\\mingw64\\binmingw32-make.exe

install:
  - set PATH=%PYTHON_HOME%;%PYTHON_HOME%/Scripts/;%PATH%
  - pip install bincrafters_package_tools
  - conan user # It creates the conan data directory

build_script:
  - cinst mingw
  - set PATH=C:\MinGW\bin;C:\tools\mingw64\bin;%PATH%
  - python build.py
